sudo: false

language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r requirements.txt

before_script:
  - python ./setup.py develop

script:
  - py.test
  - make -C test test
